### ISSUE TITLE
Shows white screen on Running

### ISSUE THREAD

**Issue by Saumik** [mdeng1024/ionic-material#1]
I cloned your repo and installed ionic material and other depencied through bower on a Mac OS with Cordova 5. Running ionic serve routes to http://localhost:8100/#/app/login but it shows a white page. Have you been able to successfully run the demo or are there any known bugs init. Please look into the matter.

Thank You

**Comment by mdeng1024** [comment]
Thanks for reporting this. Apparently, this project was broken by the new ionic-materials update. Please check out again, I have updated the project to work with the latest (as of today) from ionic and ionic-material projects.
